# Generated by Django 5.0.14 on 2025-05-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showitem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='iamge_path',
            new_name='image_path',
        ),
    ]
