# Generated by Django 5.0.14 on 2025-05-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showitem', '0003_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_file',
            field=models.FileField(default='productpic.jpg', upload_to='product_images/'),
        ),
    ]
