# Generated by Django 5.0.14 on 2025-05-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showitem', '0004_productimage_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_file',
            field=models.FileField(default='products/productpic.jpg', upload_to='product_images/'),
        ),
    ]
