# Generated by Django 5.0.14 on 2025-05-31 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showitem', '0003_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=255)),
                ('user_mail', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_system.user')),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            bases=('user_system.user',),
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showitem.product')),
                ('user_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_system.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_system.user')),
                ('rating', models.FloatField(default=0.0)),
                ('products', models.ManyToManyField(blank=True, null=True, to='showitem.product')),
            ],
            bases=('user_system.user',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ID', models.CharField(max_length=255)),
                ('products', models.CharField(blank=True, max_length=1024)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('customer_ID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_system.customer')),
                ('seller_ID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_system.seller')),
            ],
        ),
    ]
