# Generated by Django 5.0.14 on 2025-05-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showitem', '0004_productimage_image_file'),
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='products',
            field=models.ManyToManyField(blank=True, to='showitem.product'),
        ),
    ]
